baseURL = 'http://hugo-screencast-demo.s3-website-eu-west-1.amazonaws.com/'
languageCode = 'en-us'
title = 'Hugo AWS Continuous Deploy'
theme = "ananke"
[[deployment.targets]]
name = "awsbucket"
URL = "s3://hugo-screencast-demo/?region=eu-west-1"